### ISSUE TITLE
 Spotify.ahk throws 404 error if spotify hasn't played anything before use

### ISSUE THREAD

**Issue by marium0505** [CloakerSmoker/Spotify.ahk#11]
Hey!

Love your script/API for Spotify! Been using it a lot. 

I have noticed something though.
The API throws 404 errors when you do 
Spoofy.Player.LastTrack(), 
Spoofy.Player.PlayPause()
and Spoofy.Player.NextTrack()
if you use them before Spotify have played something.

In other words:
1. Open spotify
2. Use one of the above functions (it is possible the same applies to the other functions, but I haven't tested them).
3. The API will throw the below error.

And the error is not thrown when you do this:
1. Open spotify
2. Make spotify play something (using the Spotify app).
3. The functions work, and no errors are thrown. 

```
---------------------------
SpotifyShortcuts.ahk
---------------------------
Error in #include file "[PATH]\Spotify.ahk":
     404 not 2xx for request "PUT:https://api.spotify.com/v1/me/player/pause".

	Line#
	173: For index,SubHeaderArray in HeaderArray
	173: {
	174: SpotifyWinHttp.SetRequestHeader(SubHeaderArray[1], SubHeaderArray[2])  
	175: }
	177: SpotifyWinHttp.Send(body)  
	179: if (SpotifyWinHttp.Status > 299 && !noErr)  
	179: {
--->	180: Throw,{message: SpotifyWinHttp.Status . " not 2xx for request """ . method . ":" . url . """.", what: "HTTP response code not 2xx", file: A_LineFile, line: A_LineNumber}
	181: }
	183: Return,SpotifyWinHttp.ResponseText
	184: }
	188: {
	189: res.SetBodyText("Page not found")  
	190: }
	191: {

The current thread will exit.
---------------------------
OK   
---------------------------
```

**Comment by CloakerSmoker** [comment]
While the error here is expected (considering that there is no device for Spotify to control playback on), the error message is definitely not the best. 
I've pushed <https://github.com/CloakerSmoker/Spotify.ahk/commit/d3dc1ae7c8d49515a6de9ccc9e86800b7fbccd04> which will show much more descriptive error messages when possible. For example, the new error in that case is:
```
NO_ACTIVE_DEVICE: Player command failed: No active device found
```

Thanks for posting this issue, that ugly "not 2xx for request" message was there for debugging, and I never remembered to make it more "human friendly"
