### ISSUE TITLE
Error in Line 204 of Spotify.ahk 

### ISSUE THREAD

**Issue by DaHepfe** [CloakerSmoker/Spotify.ahk#14]
Hello! 
btw im a "newbie" in AHK so sorry in case my report is stupid. When i try to play a Playlist in spotify i get the message that there is a error in Line 204 in the spotify.ahk (i uploadet the error popup)

here is the code with i call the function:

`
1B07:                                              ; I call the function with a gui button

Spoofy := new Spotify()

1Playlist := Spoofy.Playlists.GetPlaylist(6JcjkR4UtyOGaR8RRp2xxx)

1Playlist.Play()
return
`

The `#Include Spotify.ahk` is in one of the first lines of my scribt.

So is that a problem with the Spotify.ahk or is the problem me?

![Unbenannt](https://user-images.githubusercontent.com/79092982/107951470-afcb9900-6f98-11eb-92bb-e4bca8404b07.PNG)

**Comment by AriGibson** [comment]
Hmmm... did you get through the authorization process successfully? That error is indicating that when Spotify.ahk makes a request to Spotify's servers, Spotify is saying that page can't be found. I just checked manually and the page definitely exists, so my best guess is that they display that error code when the authorization doesn't work properly. Which doesn't sound like a good system but 🤷‍♀️

**Comment by DaHepfe** [comment]
Yes i already tested to remove the token in the Spotify settings and authorized it again but didn´t helped. All what i get after i authorized the App is a empty website that says: "Authorization complete, closing listen server."  But when i manually open the site in the error code i get: 
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}


![Unbenannt](https://user-images.githubusercontent.com/79092982/107969220-c4675b80-6faf-11eb-8819-213d880041e5.PNG)
  This is what i see on the Spotify page under Apps

**Comment by DaHepfe** [comment]
Now i tested the code from the docs 

`
Spoofy := new Spotify()
NewPlaylist := Spoofy.Playlists.CreatePlaylist("Test 123", "This is an example playlist made by Spotify.ahk")
NewPlaylist.AddTrack("5ogtb9bGQoH8CjZNxmbNHR")
NewPlaylist.Play()
`
It dont get why this works but my code dont? I didn´t do anything except to replace my code with this example....
The only thing what comes up is that I have to accept a checkbox before the scribt do his thing:
![Unbenannt](https://user-images.githubusercontent.com/79092982/107975953-24163480-6fb9-11eb-8686-ae8fc2ed44fc.PNG)

I dont know is this normal?

**Comment by AriGibson** [comment]
Caught me just as I was responding to your message above! What OS are you on, and are you familiar with REST clients? My next recommendation is going to be to hit the endpoint with generated auth token and see if that does it.

It all just clicked for me, actually. The 404 error from the first request you made is likely indicating that a playlist with that playlist ID doesn't exist. I'd start by just using a REST client or cURL to hit the endpoint that returns all the playlist IDs

**Comment by AriGibson** [comment]
I'm doing some digging into the code though, hang on for a few min actually

**Comment by AriGibson** [comment]
Cool, I've been really overcomplicating this, sorry 😅

I haven't touched this lib or AHK in a while, but my guess is that the parameter needs to be a string. It's being misinterpreted by AHK because it doesn't have quotes around the playlist ID. Try this:

`1Playlist := Spoofy.Playlists.GetPlaylist("6JcjkR4UtyOGaR8RRp2xxx")`

**Comment by DaHepfe** [comment]
OMG ! THANKS! I put it in quotes and it works!

**Comment by AriGibson** [comment]
I'm so glad! It's always those tiny little ones that cause the most problems... 😒

Only request is that you close this issue now that it's been solved, saved the repo owner a step :)

**Comment by DaHepfe** [comment]
Ouh yes but this is why i love this!
