### ISSUE TITLE
If no LastTrack() an error is thrown

### ISSUE THREAD

**Issue by Sleuteltje** [CloakerSmoker/Spotify.ahk#15]
If there is no previous track in the currently playing list, calling LastTrack() will throw a HTTP error "page not found". 

![afbeelding](https://user-images.githubusercontent.com/6208988/111478439-605fc080-8730-11eb-9f89-6e39a576e46b.png)

**Comment by CloakerSmoker** [comment]
Well, my "fix" for this would really just be wrapping the body of the `.Player.LastTrack()` method in a [`try { ... }`](https://www.autohotkey.com/docs/commands/Try.htm), but that would silence *all* errors from that method, even those that someone might want to handle inside of their code.

Beyond that, there's not much I can do about this. It is a correct (and expected) error, so you will need to change your code to handle it. A simple [`try { ... }`](https://www.autohotkey.com/docs/commands/Try.htm) around the line calling `.Player.LastTrack()` should be enough. If you need to run some code when this error is thrown, add a [`catch { ... }`](https://www.autohotkey.com/docs/commands/Catch.htm) after.
