### ISSUE TITLE
PREMIUM_REQUIRED: Player command failed: Premium required

### ISSUE THREAD

**Issue by marium0505** [CloakerSmoker/Spotify.ahk#17]
Hey,

It looks like something Spotify has done recently broke most of Spotify.ahk. 

I keep getting Premium required errors, and some stuff simply doesn't work (such as info like Track name, album name etc. in GetCurrentPlaybackInfo).

And yes, I do have Spotify Premium.

I have made some quick additions to your example code to add stuff like Previous and next song, playback info etc. 

### Example code
The F and Media shortcuts all gives the premium required error, the F6 does not give an error, but it doesn't give any information about name, album or progress. 
  
<details>
  <summary>Show/Hide Script Example</summary>

  ```AutoHotkey
#Persistent
#SingleInstance, Force

#Include %A_ScriptDir%
#Include Spotify.ahk
global VolumePercentage
global ShuffleMode
global RepeatMode := 0
spoofy := new Spotify
VolumePercentage := spoofy.Player.GetCurrentPlaybackInfo().Device.Volume
return

F1::
  if(VolumePercentage - 1 > 0)
	VolumePercentage--
  spoofy.Player.SetVolume(VolumePercentage) ; Decrement the volume percentage and set the player to the new volume percentage
return

F2::
  VolumePercentage++
  spoofy.Player.SetVolume(VolumePercentage) ; Increment the volume percentage and set the player to the new volume percentage
return 

F3::
  ShuffleMode := !ShuffleMode
  spoofy.Player.SetShuffle(ShuffleMode) ; Swap the shuffle mode of the player
return 

F4::
  RepeatMode := RepeatMode + (RepeatMode = 0 ? 1 : (RepeatMode = 1 ? 1 : (RepeatMode = 2 ? 1 : -2)))
  spoofy.Player.SetRepeatMode(RepeatMode) ; Cycle through the three repeat modes (1-2, 2-3, 3-1)
return 

F6::
  spoofy := new Spotify
  CurrentPlayback := Spoofy.Player.GetCurrentPlaybackInfo()
  Track_Name := CurrentPlayback.Track.Name	
  Album_Name := CurrentPlayback.Track.Album.Name	
  Track_Duration := MariusAPI_FormatSeconds(Round(CurrentPlayback.Track.Duration / 1000))
  Track_Artist_Main := CurrentPlayback.Track.Artists[1].Name
  Track_Progress := MariusAPI_FormatSeconds(Round(CurrentPlayback.Progress_ms / 1000))
  Message = 
	( Join`r`n LTrim
	  Track Name: %Track_Name% 
	  Progress: %Track_Progress% / %Track_Duration%

	  Album: %Album_Name% 
	)
  MsgBox, %Message%
return 

Media_Prev::
	Spoofy.Player.LastTrack()
return 

Media_Play_Pause::
	Spoofy.Player.PlayPause()
return 

Media_Next::
	Spoofy.Player.NextTrack()
return 

  ```
  
</details>

It wasn't until recently that the errors started on stuff that worked fine before. 

<details>
  <summary>Show/Hide Code Error</summary>
  
  ```
---------------------------
Spotify Example Hotkeys.ahk
---------------------------
Error in #include file ".....\Spotify.ahk":
     PREMIUM_REQUIRED: Player command failed: Premium required

	Line#
	196: }
	198: ErrorMessage .= ErrorObject.Message  
	199: }
	200: Else
	200: {
	201: ErrorMessage := SpotifyWinHttp.Status . " not 2xx for request """ . method . ":" . url . """."
	202: }
--->	204: Throw,{message: ErrorMessage, what: "HTTP response code not 2xx", file: A_LineFile, line: A_LineNumber}
	205: }
	207: Return,SpotifyWinHttp.ResponseText
	208: }
	212: {
	213: res.SetBodyText("Page not found")  
	214: }
	215: {

The current thread will exit.
---------------------------
OK   
---------------------------

  ```
  
</details>

Any idea what's up?

**Comment by CloakerSmoker** [comment]
Well, as far as I can tell, there have been no breaking changes on the Spotify side of things, and there's no posts mentioning similar problems on the Spotify forums. I haven't gotten any emails from/about Spotify, and the Developer Dashboard looks normal.

Are you sure your premium hasn't expired or anything? I've just cloned the repo fresh and everything seems to work fine, so unless other people are having this same issue, it is more likely that this is a problem with your account.

One thing to try is deleting the registry key `HKCU\Software\SpotifyAHK`. It'll just make you do the web authorization again next time you run your script, and should clear up any problems with authorization that might exist.

Another thing to try is sending an API request through the [Spotify Developer Console](https://developer.spotify.com/console/post-next/), which is the most "official" way. If you still get the same error, then you'll want to contact Spotify support to see what's up.

**Comment by CloakerSmoker** [comment]
Oh, one last thing. You can run
```
#Include %A_ScriptDir%
#Include Spotify.ahk
Spoofy := new Spotify()

MsgBox, % Spoofy.CurrentUser.SubscriptionLevel
```

to show if the Spotify API itself thinks you are a premium account or not. It should be show ` premium` or `free`/`open`.

**Comment by marium0505** [comment]
Seems like removing the key and reauthorizing worked. 
Weird, my account has been part of a Premium Family for years now. 

Anyways: everything works again now, so thanks! :)

Closing the issue.
