### ISSUE TITLE
Add support for positions in RemoveTrack()

### ISSUE THREAD

**Issue by marium0505** [CloakerSmoker/Spotify.ahk#18]
Hey,

Could you look into adding positions in the RemoveTrack() and AddTrack() and potentially other functions where that is relevant/available, but especially the RemoveTrack function? 

I have tested positions using Spotify API console, and it works. Positions is the position of the trac in the playlist counting from 0. 
https://developer.spotify.com/console/delete-playlist-tracks/

I'm asking for this as it gives me the ability to remove one occurrence of a track rather than all of them from a playlist. 

Thanks in advance.

**Comment by CloakerSmoker** [comment]
Reading over the documentation, it seems like that option is undocumented (at least for removing tracks from playlists), and works in a different way for adding tracks. 

I might have missed something, so please send a link to whichever documentation you're using for this.

**Comment by marium0505** [comment]
Thanks for the quick reply. 

Yeah, I don't think I would have ever figured it out if I didn't look into the functions myself, and ended up in the API Console and noticed the part of position in the request body. 

```json
{
  "tracks": [
    {
      "uri": "spotify:track:2DB2zVP1LVu6jjyrvqD44z",
      "positions": [
        0
      ]
    },
    {
      "uri": "spotify:track:5ejwTEOCsaDEjvhZTcU6lg",
      "positions": [
        1
      ]
    }
  ]
}
```

I did some testing (tweaking the playlist ID to a test playlist I created with a few tracks (and some duplicates), and it did indeed work. But yeah, I haven't been able to find it documented anywhere. 

I did find this thread in the Spotify for Developers section in the Spotify forum though, which was created this February. 
[[API] Remove Items from a Playlist](https://community.spotify.com/t5/Spotify-for-Developers/API-Remove-Items-from-a-Playlist/m-p/5148296). 

I also found it here:
https://github.com/RoguePlanetoid/Spotify-NetStandard#removetracksfromplaylistasyncplaylistid-uris-snapshotid-uripositions-1 (support for Positions was added in [version 1.6.0](https://github.com/RoguePlanetoid/Spotify-NetStandard#version-160)).

That's about all I could find about it.

**Comment by CloakerSmoker** [comment]
I'm not 100% against including undocumented functionality, but I would want to put it behind a big scary `Spotify.ALLOW_UNDOCUMENTED_FUNCTIONALITY` field or something similar. On top of that, I'm a bit too busy with other things to test/implement this right now, sorry.

However, I can point you in the right direction for implementing it yourself:

- First, you'll want to add another option like `static SHOULD_CHECK_CONNECTION_BEFORE_REQUEST := false` in the core `Spotify` class (Ignore this step if you're just modifying for personal use)
- Then you will need to want to edit this (https://github.com/CloakerSmoker/Spotify.ahk/blob/master/Spotify.ahk#L501) function to take an extra parameter (with a default value, to not break existing code) for the positions. 
- Then, you'll just need to check that `Spotify.WHATEVER_YOU_NAME_IT` option before sticking the extra parameter into `JSON.Dump({"tracks": [{"uri": "spotify:track:" . tid}]})` (that final parameter is the body of the API request, so adding the `positions` array to the object with the `"uri"` property should be fine)

And finally, to use the feature, just set `Spotify.WHATEVER_YOU_NAME_THE_FLAG := true` in your script, and you'll be good to go.
