### ISSUE TITLE
Is there a way to generate new token?

### ISSUE THREAD

**Issue by darekdani** [CloakerSmoker/Spotify.ahk#19]
I logged in with my other account which is premium, but it just gives me the error "Premium required" when i wanna use things.
I assume it's still tied to my previous account. 
**https://api.spotify.com/v1/** gives me **401 No token provide** message.

Is there a way to fix it?

**Comment by darekdani** [comment]
![Premium required error](https://i.imgur.com/dmoP7Tj.jpg)

**Comment by CloakerSmoker** [comment]
Deleting the registry key `HKCU\Software\SpotifyAHK` will have you go through the auth flow again (with whichever account you want)

**Comment by darekdani** [comment]
> 
> 
> Deleting the registry key `HKCU\Software\SpotifyAHK` will have you go through the auth flow again (with whichever account you want)

That's works, thanks.
