### ISSUE TITLE
Error 400 when opening example hotkeys for the first time

### ISSUE THREAD

**Issue by queendasher** [CloakerSmoker/Spotify.ahk#7]
When I run Example Hotkeys.ahk for the first time to get the prompt to authorize the app, all I get is this

I've googled for over 2 hours now to try and fix this, and I'm slowly losing my mind here. Not very savvy with this API auth token thing.

**Comment by CloakerSmoker** [comment]
Hmm, it looks like your refresh token might be invalid, try deleting the registry key `HKCU\Software\SpotifyAHK\RefreshToken` and running it again. 
This will clear the refresh token that stops you from having to do the authorization in the browser each time you use the library. 
Running it again should open your browser again and redo the authorization.

If this doesn't fix it, edit line 124 of `Spotify.ahk` to 
`throw {message: SpotifyWinHttp.Status . " not 4xx, response body:" SpotifyWinHttp.ResponseText, what: "HTTP response code not 2xx", file: A_LineFile, line: A_LineNumber}`
This will alter the error message to include what the Spotify API thinks went wrong with the request, which will a lot help with fixing the problem.

You might want to edit out that picture, as if that refresh token isn't actually invalid, it could be used by someone else to authorize them self as your account in the eyes of the Spotify API.

**Comment by queendasher** [comment]
All fixed and working, finally some global volume control. Thanks, you absolute legend!
